[tool.poetry]
name = "noisemon"
version = "0.3.0"
description = "Module for listening informational noise and making some stats"
authors = ["Max Ermakov <maksim_ermakov@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^1.8.2"
python-dotenv = "^0.18.0"
regex = "^2021.7.6"
SPARQLWrapper = "^1.8.5"
Telethon = "^1.23.0"
SQLAlchemy = "1.4.26"
faiss-cpu = "^1.7.1"
reticker = "^3.1.3"
dill = "^0.3.4"
torch = "^1.9.1"
pika = "^1.2.0"
spacy = "^3.2.0"
spacy-transformers = "^1.1.2"
Cython = "^0.29.24"


[tool.poetry.dev-dependencies]
ipykernel = "^6.0.1"
pylint = "^2.9.3"
notebook = "^6.4.0"
black = {version = "^21.7b0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
