[tool.poetry]
name = "noisemon"
version = "0.4.0"
description = "NEL pipeline Integrated with KB"
authors = ["Max Ermakov <maksim_ermakov@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^1.8.2"
python-dotenv = "^0.18.0"
regex = "^2021.7.6"
SPARQLWrapper = "^1.8.5"
Telethon = "^1.23.0"
SQLAlchemy = "1.4.26"
faiss-cpu = "^1.7.1"
reticker = "^3.1.3"
dill = "^0.3.4"
torch = "^1.9.1"
pika = "^1.2.0"
spacy = "^3.2.0"
spacy-transformers = "^1.1.2"
Cython = "^0.29.24"
dateparser = "^1.1.0"
psycopg2-binary = "^2.9.2"
redis = "^4.0.2"
pyfuseki = "^1.6"


[tool.poetry.dev-dependencies]
ipykernel = "^6.0.1"
pylint = "^2.9.3"
notebook = "^6.4.0"
black = {version = "^21.7b0", allow-prereleases = true}
sklearn = "^0.0"
types-dateparser = "^1.0.8"
SQLAlchemy-Utils = "^0.37.9"
jupyterlab = "^3.2.8"
newspaper3k = "^0.2.8"
readability-lxml = "^0.8.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[mypy]
python_version = 3.8
warn_return_any = true
ignore_missing_imports = true
warn_unused_configs = true
mypy_path = "$MYPY_CONFIG_FILE_DIR/noisemon/"
files = "$MYPY_CONFIG_FILE_DIR/noisemon/**/*.py"
exclude = "$MYPY_CONFIG_FILE_DIR/noisemon/**/*.test.py"
python_executable = "$MYPY_CONFIG_FILE_DIR/.venv/bin/python"

